const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('api', {
  getSettings: () => ipcRenderer.invoke('get-settings'),
  setSettings: (settings) => ipcRenderer.invoke('set-settings', settings),
  attendanceList: () => ipcRenderer.invoke('attendance-list'),
  attendanceListFull: () => ipcRenderer.invoke('attendance-list-full'),
  attendanceSearch: (params) => ipcRenderer.invoke('attendance-search', params),
  attendanceGet: (id) => ipcRenderer.invoke('attendance-get', id),
  attendanceSave: (payload) => ipcRenderer.invoke('attendance-save', payload),
  attendanceDelete: (params) => ipcRenderer.invoke('attendance-delete', params),
  attendanceArchive: (id) => ipcRenderer.invoke('attendance-archive', id),
  attendanceUnarchive: (id) => ipcRenderer.invoke('attendance-unarchive', id),
  attendanceCheckDuplicate: (params) => ipcRenderer.invoke('attendance-check-duplicate', params),
  stationsList: () => ipcRenderer.invoke('stations-list'),
  stationsReplace: (stations) => ipcRenderer.invoke('stations-replace', stations),
  firmsList: () => ipcRenderer.invoke('firms-list'),
  firmSave: (firm) => ipcRenderer.invoke('firm-save', firm),
  firmDelete: (id) => ipcRenderer.invoke('firm-delete', id),
  firmSetDefault: (id) => ipcRenderer.invoke('firm-set-default', id),
  generateUfn: (dateStr) => ipcRenderer.invoke('generate-ufn', dateStr),
  loadReferenceData: () => ipcRenderer.invoke('load-reference-data'),
  saveCsv: (payload) => ipcRenderer.invoke('save-csv', payload),
  backupNow: () => ipcRenderer.invoke('backup-now'),
  dbRepair: () => ipcRenderer.invoke('db-repair'),
  getDesktopPath: () => ipcRenderer.invoke('get-desktop-path'),
  getDbPath: () => ipcRenderer.invoke('get-db-path'),
  setRecoveryPassword: (pw) => ipcRenderer.invoke('set-recovery-password', pw),
  hasRecoveryPassword: () => ipcRenderer.invoke('has-recovery-password'),
  recoverKeyFromCloud: () => ipcRenderer.invoke('recover-key-from-cloud'),
  isDbEncrypted: () => ipcRenderer.invoke('is-db-encrypted'),
  isSafeStorageAvailable: () => ipcRenderer.invoke('is-safe-storage-available'),
  chooseFolder: (opts) => ipcRenderer.invoke('choose-folder', opts || {}),
  detectCloudFolders: () => ipcRenderer.invoke('detect-cloud-folders'),
  openExternal: (url) => ipcRenderer.invoke('open-external', url),
  openPath: (filePath) => ipcRenderer.invoke('open-path', filePath),
  printToPdf: (options) => ipcRenderer.invoke('print-to-pdf', options),
  printPdfFile: (filePath) => ipcRenderer.invoke('print-pdf-file', filePath),
  quickfileFetchInvoices: () => ipcRenderer.invoke('quickfile-fetch-invoices'),
  quickfileFetchClients: () => ipcRenderer.invoke('quickfile-fetch-clients'),
  pickImage: () => ipcRenderer.invoke('pick-image'),
  pickFile: () => ipcRenderer.invoke('pick-file'),
  importRecordFromFile: () => ipcRenderer.invoke('import-record-from-file'),
  importRecordFromPath: (filePath) => ipcRenderer.invoke('import-record-from-path', filePath),
  onAutoImportImported: (cb) => ipcRenderer.on('auto-import:imported', (_, payload) => cb(payload)),
  onAutoImportError: (cb) => ipcRenderer.on('auto-import:error', (_, payload) => cb(payload)),
  /* Audit & compliance */
  auditLogGet: (id) => ipcRenderer.invoke('audit-log-get', id),
  supervisorApprove: (params) => ipcRenderer.invoke('supervisor-approve', params),
  getAppVersion: () => ipcRenderer.invoke('get-app-version'),
  getBankHolidays: () => ipcRenderer.invoke('get-bank-holidays'),
  /* Photo file storage */
  photoSave: (params) => ipcRenderer.invoke('photo-save', params),
  photoLoad: (params) => ipcRenderer.invoke('photo-load', params),
  photoDelete: (params) => ipcRenderer.invoke('photo-delete', params),
  /* LAA Official PDF forms */
  laaGenerateOfficialPdf: (params) => ipcRenderer.invoke('laa-generate-official-pdf', params),
  laaOpenOfficialTemplate: (formType) => ipcRenderer.invoke('laa-open-official-template', formType),
  /* Licence */
  licenceStatus: () => ipcRenderer.invoke('licence:status'),
  licenceActivate: (params) => ipcRenderer.invoke('licence:activate', params),
  licenceValidate: () => ipcRenderer.invoke('licence:validate'),
  licenceDeactivate: () => ipcRenderer.invoke('licence:deactivate'),
  licenceEmailKey: () => ipcRenderer.invoke('licence:email-key'),
  licenceDeactivateMachine: () => ipcRenderer.invoke('licence:deactivate-machine'),
  prepareTrial: () => ipcRenderer.invoke('prepare-trial'),
  getS3BackupStatus: () => ipcRenderer.invoke('get-s3-backup-status'),
  testS3Backup: () => ipcRenderer.invoke('test-s3-backup'),
  onS3BackupStatus: (cb) => ipcRenderer.on('s3-backup-status', () => cb()),
  /* Managed cloud backup */
  cloudBackupStatus: () => ipcRenderer.invoke('cloud-backup-status'),
  cloudBackupCheckEntitlement: () => ipcRenderer.invoke('cloud-backup-check-entitlement'),
  cloudBackupSubscribe: () => ipcRenderer.invoke('cloud-backup-subscribe'),
  cloudBackupList: () => ipcRenderer.invoke('cloud-backup-list'),
  cloudBackupRestore: (params) => ipcRenderer.invoke('cloud-backup-restore', params),
  onCloudBackupStatusChanged: (cb) => ipcRenderer.on('cloud-backup-status-changed', (_, data) => cb(data)),
  /* Cross-device sync */
  syncNow: () => ipcRenderer.invoke('sync-now'),
  syncStatus: () => ipcRenderer.invoke('sync-status'),
  syncScheduleOnReconnect: () => ipcRenderer.invoke('sync-schedule-on-reconnect'),
  syncGetDiagnostics: () => ipcRenderer.invoke('sync-get-diagnostics'),
  attendanceHomeStats: () => ipcRenderer.invoke('attendance-home-stats'),
  syncForceRetry: () => ipcRenderer.invoke('sync-force-retry'),
  onSyncStatusChanged: (cb) => ipcRenderer.on('sync-status-changed', (_, data) => cb(data)),
  onRecordsUpdatedFromSync: (cb) => ipcRenderer.on('records-updated-from-sync', (_, data) => cb(data)),
  /* Auto-update */
  onAppUpdateStatus: (cb) => ipcRenderer.on('app-update-status', (_, data) => cb(data)),
  appUpdateInstall: () => ipcRenderer.invoke('app-update-install'),
  appCheckUpdates: () => ipcRenderer.invoke('app-check-updates'),
});

contextBridge.exposeInMainWorld('custodyNote', {
  requestLicenceEmail: (email) => ipcRenderer.invoke('custody:requestLicenceEmail', email),
  adminLogin: (password) => ipcRenderer.invoke('custody:adminLogin', password),
  adminSetPassword: (opts) => ipcRenderer.invoke('custody:adminSetPassword', opts),
  adminHasPassword: () => ipcRenderer.invoke('custody:adminHasPassword'),
  adminSearch: (emailQuery) => ipcRenderer.invoke('custody:adminSearch', emailQuery),
  adminRevealLicence: (id) => ipcRenderer.invoke('custody:adminRevealLicence', id),
  adminResend: (id) => ipcRenderer.invoke('custody:adminResend', id),
  adminSync: () => ipcRenderer.invoke('custody:adminSync'),
  serverConfigured: () => ipcRenderer.invoke('custody:serverConfigured'),
});
